"""
Global constant definitions
"""
tf_cpp_min_log_level = 2

# Flags passed to ImageMagick to convert DICOMs to PNGs. This should be
# kept in sync with the variable in preprocess.sh.
# IMAGE_MAGICK_FLAGS = '-depth 8 -resize {}x{}! -colorspace sRGB'.format(WIDTH, HEIGHT)

dir_prefix = '../results/mammo'

# Location to save the trained model
model_state_dir = dir_prefix + '/model_state'

# Name of the trained model file.
model_filename = 'trained.h5'

# File containing scores generated by trained model.
predictions_file = dir_prefix + '/output/predictions.tsv'

