# Global constant definitions

import os

TF_CPP_MIN_LOG_LEVEL = 2

LABELS = ['benign', 'normal', 'malevolent']

# Dimensions of the images that will be used for classification and training.
WIDTH = 224
HEIGHT = 224

# Flags passed to ImageMagick to convert DICOMs to PNGs. This should be
# kept in sync with the variable in preprocess.sh.
IMAGE_MAGICK_FLAGS = '-depth 8 -resize {}x{}! -colorspace sRGB'.format(WIDTH, HEIGHT)

DIR_PREFIX = '../data'

# Directory where raw .dcm training images are stored according to challenge guidelines.
TRAIN_IMG_DIR = DIR_PREFIX + '/train_data'

# Directory where raw .dcm inference images are stored according to challenge guidelines.
INFERENCE_IMG_DIR = DIR_PREFIX + '/inference_data'

# Directory where preprocessed data can be saved according to challenge guidelines.
PREPROCESS_DIR = DIR_PREFIX + '/preprocessed_data'

# Directory where preprocessed images are stored.
PREPROCESS_IMG_DIR = PREPROCESS_DIR + '/images'

# Location where exams_metadata.tsv is stored according to challenge guidelines.
EXAMS_METADATA_FILE = DIR_PREFIX + '/metadata/exams_metadata.tsv'

# Location where images_crosswalk.tsv is stored according to challenge guidelines.
IMAGES_CROSSWALK_FILE = DIR_PREFIX + '/metadata/images_crosswalk.tsv'

# Location to save the trained model according to challenge guidelines.
MODELSTATE_DIR = DIR_PREFIX + '/model_state'

# Name of the trained model file.
MODEL_FILENAME = 'trained.h5'

# File containing scores generated by trained model.
OUTPUT_FILEPATH = DIR_PREFIX + '/output/predictions.tsv'
