# Global constant definitions

TF_CPP_MIN_LOG_LEVEL = 2

# Flags passed to ImageMagick to convert DICOMs to PNGs. This should be
# kept in sync with the variable in preprocess.sh.
# IMAGE_MAGICK_FLAGS = '-depth 8 -resize {}x{}! -colorspace sRGB'.format(WIDTH, HEIGHT)

DIR_PREFIX = '../data'

# Location to save the trained model
MODEL_STATE_DIR = DIR_PREFIX + '/model_state'

# Name of the trained model file.
MODEL_FILENAME = 'trained.h5'

# File containing scores generated by trained model.
PREDICTIONS_FILE = DIR_PREFIX + '/output/predictions.tsv'
