# -*- coding: utf-8 -*-
"""
  labels: true label of the image set
  data_dir: source data location
  input_shape: Shape of the image to feed in the model

data_src:
  ddsm:
  mias: 1024 x 1024 x 3,
  cifar10: 32 x 32 x 3, 50000 and 10000
  mnist: 28 x 28 x 1,  60000 and 10000
"""
src_data_configs = {
    'ddsm': {
        'labels': {'normal': 0, 'benign': 1, 'cancer': 2},
        'data_dir': '/data/ddsm',
        'input_shape': (400, 250, 1)  # Original image is RGB, (400, 250, 1)
                                      # (500, 300, 1) triggers OOM error
    },
    'mias': {
        'labels': {'NORMAL': 0, 'CANCER': 1},
        'data_dir': '/data/mias',
        'input_shape': (224, 224, 3)
    },
    'mnist': {
        'labels': {'{}'.format(x): x for x in range(10)},  # NB xheng: Not used really
        'data_dir': '',
        'input_shape': (28, 28, 1)
    },
    'cifar10': {
        'labels': {'{}'.format(x): x for x in range(10)},  # NB xheng: Not really used
        'data_dir': '',
        'input_shape': (32, 32, 3)
    }
}

results_dir = '../results/mammo/{data_src}'  # this is location of project root

model_state_dir = results_dir + '/model_state'

model_filename = 'trained.h5'  # Name of the trained model file

# File containing scores generated by trained model.
predictions_file = results_dir + '/output/predictions.tsv'

