# -*- coding: utf-8 -*-
"""
  labels: true label of the image set
  data_dir: source data location
  input_shape: Shape of the image
"""
src_data_configs = {
    'ddsm': {
        'labels': {'normal': 0, 'benign': 1, 'cancer': 2},
        'data_dir': '/data/ddsm',
        'input_shape': (224, 224, 1)  # (224, 224, 3)
    },
    'mias': {
        'labels': {'NORMAL': 0, 'CANCER': 1},
        'data_dir': '/data/mias',
        'input_shape': (224, 224, 1)
    },
    'mnist': {
        'labels': {'{}'.format(x): x for x in range(10)},  # NB xheng: Not used really
        'data_dir': '',
        'input_shape': (28, 28, 1)
    },
    'cifar10': {
        'labels': {'{}'.format(x): x for x in range(10)},  # NB xheng: Not really used
        'data_dir': '',
        'input_shape': (32, 32, 3)
    }
}

results_dir = '../results/mammo/{data_src}'  # this is locaiton of project root

model_state_dir = results_dir + '/model_state'

model_filename = 'trained.h5'  # Name of the trained model file

# File containing scores generated by trained model.
predictions_file = results_dir + '/output/predictions.tsv'

